name: Update this repo's README

on:
  #workflow_dispatch
  schedule:
    # Once a day at 9 AM
    - cron: 0 9 * * *

  
jobs:
  pull_blog_rss:
    name: Update with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://www.stefanobaccianella.com/feed
      - name: Commit file changes
        run: |
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git diff --quiet --cached || git commit -m "Update README"
            git push
